push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Download YOLOv8 AnimeFace model
        run: |
          curl -L -o yolov8_animeface.onnx https://huggingface.co/Fuyucch1/yolov8_animeface/resolve/main/yolov8_animeface.onnx?download=true

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole app.py --name app
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cartoon-face-blur-exe
          path: dist/app.exe
